### ISSUE TITLE
[Irrelevant] I'm so sorry to leave you a message here but since the hapflk-pool issue is closed I didn't know how to contact you

### ISSUE THREAD

**Issue by BioInfoNoob** [magicDGS/jsr203-http#62]
Could I get your email address or something to ask you about the Hapflk tool? I'm so sorry for issuing it here

**Comment by magicDGS** [comment]
Please, if you refer to https://github.com/magicDGS/hapflk_pool, the README clearly states that the development happen under  https://github.com/magicDGS/poolFLK. Please, ask your question there as this repo library is for different purposes.. Although it is a long time since I don't improve the tool, I sometimes pass by to check the questions.
